package be.gim.tov.osyris.model.werk.status;

/**
 * 
 * @author kristof
 * 
 */
public enum WerkopdrachtStatus {

	TE_CONTROLEREN, UIT_TE_VOEREN, GEANNULEERD, GERAPPORTEERD, GEVALIDEERD_OPNIEUW_UITVOEREN, GEVALIDEERD_NIET_OPNIEUW_UITVOEREN, GEVALIDEERD_LATER_OPNIEUW_UITVOEREN_VANAF, GEVALIDEERD_FOUT_GERAPPORTEERD, GEVALIDEERD_OK_VOOR_FACTURATIE, UITGESTELD
}
