package be.gim.tov.osyris.model.controle.status;

public enum ControleOpdrachtStatus {

	TE_CONTROLEREN, UIT_TE_VOEREN, UITGESTELD, GEANNULEERD, GERAPPORTEERD, GEVALIDEERD_WERKOPDRACHT, GEVALIDEERD_GEEN_WERKOPRDACHT, GEVALIDEERD_REEDS_GEMELD, GEVALIDEERD_IN_BEHANDELING
}
